{{- if .Values.workers.autoscaler.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "es.release_labels" . | indent 4 }}
  name: worker-auto-scale
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}-worker
  minReplicas: {{ required "workers.replicaCount must be provided."  .Values.workers.replicaCount }}
  maxReplicas: {{ required "workers.autoscaler.maxReplicas must be provided." .Values.workers.autoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: 75
{{- end -}}
